
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/

#pragma once
#include <array>
#include <string_view>

namespace cxx {

namespace fn {
namespace sf {
namespace PlaybackDevice {
namespace setDevice {
    inline constexpr std::string_view id = "sf::PlaybackDevice::setDevice";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "bool(const std::string &)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace getVelocity {
    inline constexpr std::string_view id = "sf::Listener::getVelocity";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Vector3f(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace getPosition {
    inline constexpr std::string_view id = "sf::Listener::getPosition";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Vector3f(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace Joystick {
namespace update {
    inline constexpr std::string_view id = "sf::Joystick::update";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace getCone {
    inline constexpr std::string_view id = "sf::Listener::getCone";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Listener::Cone(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace swap {
    inline constexpr std::string_view id = "sf::swap";
    inline constexpr std::array<std::string_view, 2> signatures = {
        "void(sf::Texture &, sf::Texture &)",
        "void(sf::VertexBuffer &, sf::VertexBuffer &)"
    };
}}}

namespace fn {
namespace sf {
namespace sleep {
    inline constexpr std::string_view id = "sf::sleep";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(sf::Time)"
    };
}}}

namespace fn {
namespace sf {
namespace Listener {
namespace getGlobalVolume {
    inline constexpr std::string_view id = "sf::Listener::getGlobalVolume";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "float(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace getDirection {
    inline constexpr std::string_view id = "sf::Listener::getDirection";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Vector3f(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace setPosition {
    inline constexpr std::string_view id = "sf::Listener::setPosition";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const sf::Vector3f &)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace setVelocity {
    inline constexpr std::string_view id = "sf::Listener::setVelocity";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const sf::Vector3f &)"
    };
}}}}

namespace fn {
namespace sf {
namespace Mouse {
namespace isButtonPressed {
    inline constexpr std::string_view id = "sf::Mouse::isButtonPressed";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "bool(sf::Mouse::Button)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace setCone {
    inline constexpr std::string_view id = "sf::Listener::setCone";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const sf::Listener::Cone &)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace setDirection {
    inline constexpr std::string_view id = "sf::Listener::setDirection";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const sf::Vector3f &)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace setUpVector {
    inline constexpr std::string_view id = "sf::Listener::setUpVector";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const sf::Vector3f &)"
    };
}}}}

namespace fn {
namespace sf {
namespace Listener {
namespace getUpVector {
    inline constexpr std::string_view id = "sf::Listener::getUpVector";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Vector3f(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace Sensor {
namespace getValue {
    inline constexpr std::string_view id = "sf::Sensor::getValue";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Vector3f(sf::Sensor::Type)"
    };
}}}}

namespace fn {
namespace sf {
namespace Clipboard {
namespace getString {
    inline constexpr std::string_view id = "sf::Clipboard::getString";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::String(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace err {
    inline constexpr std::string_view id = "sf::err";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "std::ostream &(void)"
    };
}}}

namespace fn {
namespace sf {
namespace Clipboard {
namespace setString {
    inline constexpr std::string_view id = "sf::Clipboard::setString";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const sf::String &)"
    };
}}}}

namespace fn {
namespace sf {
namespace Keyboard {
namespace localize {
    inline constexpr std::string_view id = "sf::Keyboard::localize";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Keyboard::Key(sf::Keyboard::Scan)"
    };
}}}}

namespace fn {
namespace sf {
namespace Mouse {
namespace getPosition {
    inline constexpr std::string_view id = "sf::Mouse::getPosition";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Vector2i(void)"
    };
}}}}

namespace fn {
namespace sf {
namespace Keyboard {
namespace isKeyPressed {
    inline constexpr std::string_view id = "sf::Keyboard::isKeyPressed";
    inline constexpr std::array<std::string_view, 2> signatures = {
        "bool(sf::Keyboard::Key)",
        "bool(sf::Keyboard::Scan)"
    };
}}}}

namespace fn {
namespace sf {
namespace Keyboard {
namespace delocalize {
    inline constexpr std::string_view id = "sf::Keyboard::delocalize";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Keyboard::Scan(sf::Keyboard::Key)"
    };
}}}}

namespace fn {
namespace sf {
namespace Keyboard {
namespace getDescription {
    inline constexpr std::string_view id = "sf::Keyboard::getDescription";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::String(sf::Keyboard::Scan)"
    };
}}}}

namespace fn {
namespace sf {
namespace Mouse {
namespace setPosition {
    inline constexpr std::string_view id = "sf::Mouse::setPosition";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(sf::Vector2i)"
    };
}}}}

namespace fn {
namespace sf {
namespace Sensor {
namespace isAvailable {
    inline constexpr std::string_view id = "sf::Sensor::isAvailable";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "bool(sf::Sensor::Type)"
    };
}}}}

namespace type {
namespace sf {
namespace Ftp {
namespace ListingResponse {
    inline constexpr std::string_view id = "sf::Ftp::ListingResponse";
}}}}


namespace type {
namespace sf {
namespace Ftp {
namespace Response {
    inline constexpr std::string_view id = "sf::Ftp::Response";
}}}}

namespace type {
namespace sf {
namespace Ftp {
namespace Response {
namespace fn {
namespace isOk {
    inline constexpr std::string_view id = "isOk";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "bool(void)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Ftp {
namespace Response {
namespace fn {
namespace getStatus {
    inline constexpr std::string_view id = "getStatus";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Ftp::Response::Status(void)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Ftp {
namespace Response {
namespace fn {
namespace getMessage {
    inline constexpr std::string_view id = "getMessage";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "const std::string &(void)"
    };
}}}}}}


namespace type {
namespace sf {
namespace Ftp {
namespace DirectoryResponse {
    inline constexpr std::string_view id = "sf::Ftp::DirectoryResponse";
}}}}

namespace type {
namespace sf {
namespace Ftp {
namespace DirectoryResponse {
namespace fn {
namespace getDirectory {
    inline constexpr std::string_view id = "getDirectory";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "const std::filesystem::path &(void)"
    };
}}}}}}


namespace type {
namespace sf {
namespace Http {
namespace Request {
    inline constexpr std::string_view id = "sf::Http::Request";
}}}}

namespace type {
namespace sf {
namespace Http {
namespace Request {
namespace fn {
namespace setField {
    inline constexpr std::string_view id = "setField";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const std::string &, const std::string &)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Http {
namespace Request {
namespace fn {
namespace setMethod {
    inline constexpr std::string_view id = "setMethod";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(sf::Http::Request::Method)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Http {
namespace Request {
namespace fn {
namespace setBody {
    inline constexpr std::string_view id = "setBody";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const std::string &)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Http {
namespace Request {
namespace fn {
namespace setUri {
    inline constexpr std::string_view id = "setUri";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "void(const std::string &)"
    };
}}}}}}


namespace type {
namespace sf {
namespace Http {
namespace Response {
    inline constexpr std::string_view id = "sf::Http::Response";
}}}}

namespace type {
namespace sf {
namespace Http {
namespace Response {
namespace fn {
namespace getStatus {
    inline constexpr std::string_view id = "getStatus";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "sf::Http::Response::Status(void)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Http {
namespace Response {
namespace fn {
namespace getField {
    inline constexpr std::string_view id = "getField";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "const std::string &(const std::string &)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Http {
namespace Response {
namespace fn {
namespace getMajorHttpVersion {
    inline constexpr std::string_view id = "getMajorHttpVersion";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "unsigned int(void)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Http {
namespace Response {
namespace fn {
namespace getMinorHttpVersion {
    inline constexpr std::string_view id = "getMinorHttpVersion";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "unsigned int(void)"
    };
}}}}}}

namespace type {
namespace sf {
namespace Http {
namespace Response {
namespace fn {
namespace getBody {
    inline constexpr std::string_view id = "getBody";
    inline constexpr std::array<std::string_view, 1> signatures = {
        "const std::string &(void)"
    };
}}}}}}


}