
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/

#pragma once
#include <vector>

#include "rtl_builder.h"


namespace regs3::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs8::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs62::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs65::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs71::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs43::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs48::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs78::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs76::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs79::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs80::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs82::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs84::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs10::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs2::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs66::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs66::type1 {
    void init(std::vector<rtl::Function>&);
}


namespace regs34::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs11::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs25::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs6::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs7::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs9::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs22::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs72::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs20::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs94::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs21::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs31::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs23::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs24::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs26::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs30::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs32::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs33::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs37::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs38::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs39::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs47::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs40::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs41::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs42::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs43::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs45::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs53::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs46::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs48::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs56::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs54::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs49::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs83::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs51::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs51::type1 {
    void init(std::vector<rtl::Function>&);
}


namespace regs51::type2 {
    void init(std::vector<rtl::Function>&);
}


namespace regs51::type3 {
    void init(std::vector<rtl::Function>&);
}


namespace regs52::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs52::type1 {
    void init(std::vector<rtl::Function>&);
}


namespace regs52::type2 {
    void init(std::vector<rtl::Function>&);
}


namespace regs55::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs57::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs64::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs58::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs59::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs61::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs63::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs73::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs95::type0 {
    void init(std::vector<rtl::Function>&);
}

