
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/

#pragma once
#include <vector>

#include "rtl_builder.h"


namespace regs65::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs43::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs3::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs8::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs48::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs62::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs71::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs76::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs78::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs79::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs80::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs82::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs84::fn {
    void init(std::vector<rtl::Function>&);
}


namespace regs51::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs51::type1 {
    void init(std::vector<rtl::Function>&);
}


namespace regs51::type2 {
    void init(std::vector<rtl::Function>&);
}


namespace regs52::type0 {
    void init(std::vector<rtl::Function>&);
}


namespace regs52::type1 {
    void init(std::vector<rtl::Function>&);
}

