
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <vector>

#include "../reg_decls.h"

namespace cxx { 

    const rtl::CxxMirror& mirror()
    {
        static auto mirror = rtl::CxxMirror([]() {

            std::vector<rtl::Function> fns;

            regs3::fn::init(fns);
            regs8::fn::init(fns);
            regs62::fn::init(fns);
            regs65::fn::init(fns);
            regs71::fn::init(fns);
            regs43::fn::init(fns);
            regs48::fn::init(fns);
            regs78::fn::init(fns);
            regs76::fn::init(fns);
            regs79::fn::init(fns);
            regs80::fn::init(fns);
            regs82::fn::init(fns);
            regs84::fn::init(fns);
            regs10::type0::init(fns);
            regs2::type0::init(fns);
            regs66::type0::init(fns);
            regs66::type1::init(fns);
            regs34::type0::init(fns);
            regs11::type0::init(fns);
            regs25::type0::init(fns);
            regs6::type0::init(fns);
            regs7::type0::init(fns);
            regs9::type0::init(fns);
            regs22::type0::init(fns);
            regs72::type0::init(fns);
            regs20::type0::init(fns);
            regs94::type0::init(fns);
            regs21::type0::init(fns);
            regs31::type0::init(fns);
            regs23::type0::init(fns);
            regs24::type0::init(fns);
            regs26::type0::init(fns);
            regs30::type0::init(fns);
            regs32::type0::init(fns);
            regs33::type0::init(fns);
            regs37::type0::init(fns);
            regs38::type0::init(fns);
            regs39::type0::init(fns);
            regs47::type0::init(fns);
            regs40::type0::init(fns);
            regs41::type0::init(fns);
            regs42::type0::init(fns);
            regs43::type0::init(fns);
            regs45::type0::init(fns);
            regs53::type0::init(fns);
            regs46::type0::init(fns);
            regs48::type0::init(fns);
            regs56::type0::init(fns);
            regs54::type0::init(fns);
            regs49::type0::init(fns);
            regs83::type0::init(fns);
            regs51::type0::init(fns);
            regs51::type1::init(fns);
            regs51::type2::init(fns);
            regs51::type3::init(fns);
            regs52::type0::init(fns);
            regs52::type1::init(fns);
            regs52::type2::init(fns);
            regs55::type0::init(fns);
            regs57::type0::init(fns);
            regs64::type0::init(fns);
            regs58::type0::init(fns);
            regs59::type0::init(fns);
            regs61::type0::init(fns);
            regs63::type0::init(fns);
            regs73::type0::init(fns);
            regs95::type0::init(fns);
            return fns;
        }());
        return mirror;
    }
}