
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <vector>

#include "../reg_decls.h"

namespace cxx { 

    const rtl::CxxMirror& mirror()
    {
        static auto mirror = rtl::CxxMirror([]() {

            std::vector<rtl::Function> fns;

            regs65::fn::init(fns);
            regs43::fn::init(fns);
            regs3::fn::init(fns);
            regs8::fn::init(fns);
            regs48::fn::init(fns);
            regs62::fn::init(fns);
            regs71::fn::init(fns);
            regs76::fn::init(fns);
            regs78::fn::init(fns);
            regs79::fn::init(fns);
            regs80::fn::init(fns);
            regs51::type0::init(fns);
            regs51::type1::init(fns);
            regs51::type2::init(fns);
            regs52::type0::init(fns);
            regs52::type1::init(fns);
            return fns;
        }());
        return mirror;
    }
}