
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/SoundBufferRecorder.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs11::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::SoundBufferRecorder>(cxx::type::sf::SoundBufferRecorder::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::SoundBufferRecorder>()
                                 .methodConst(cxx::type::sf::SoundBufferRecorder::fn::getBuffer::id)
                                 .build(&sf::SoundBufferRecorder::getBuffer));
    }
}

