
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/SoundBuffer.hpp>
#include <SFML/System/Time.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs10::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::SoundBuffer>(cxx::type::sf::SoundBuffer::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .methodConst(cxx::type::sf::SoundBuffer::fn::getChannelCount::id)
                                 .build(&sf::SoundBuffer::getChannelCount));

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .constructor<const std::filesystem::path &>().build());

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .constructor<const void *, unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .method(cxx::type::sf::SoundBuffer::fn::loadFromFile::id)
                                 .build(&sf::SoundBuffer::loadFromFile));

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .methodConst(cxx::type::sf::SoundBuffer::fn::saveToFile::id)
                                 .build(&sf::SoundBuffer::saveToFile));

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .methodConst(cxx::type::sf::SoundBuffer::fn::getSampleRate::id)
                                 .build(&sf::SoundBuffer::getSampleRate));

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .methodConst(cxx::type::sf::SoundBuffer::fn::getSamples::id)
                                 .build(&sf::SoundBuffer::getSamples));

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .method(cxx::type::sf::SoundBuffer::fn::loadFromMemory::id)
                                 .build(&sf::SoundBuffer::loadFromMemory));

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .methodConst(cxx::type::sf::SoundBuffer::fn::getSampleCount::id)
                                 .build(&sf::SoundBuffer::getSampleCount));

        fns.push_back(rtl::type().member<sf::SoundBuffer>()
                                 .methodConst(cxx::type::sf::SoundBuffer::fn::getDuration::id)
                                 .build(&sf::SoundBuffer::getDuration));
    }
}

