
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/Font.hpp>
#include <SFML/System/InputStream.hpp>
#include <SFML/Graphics/Glyph.hpp>
#include <SFML/Graphics/Texture.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs26::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Font>(cxx::type::sf::Font::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Font>()
                                 .constructor<const std::filesystem::path &>().build());

        fns.push_back(rtl::type().member<sf::Font>()
                                 .constructor<const void *, unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::Font>()
                                 .constructor<sf::InputStream &>().build());

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::getGlyph::id)
                                 .build(&sf::Font::getGlyph));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .method(cxx::type::sf::Font::fn::openFromFile::id)
                                 .build(&sf::Font::openFromFile));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .method(cxx::type::sf::Font::fn::openFromMemory::id)
                                 .build(&sf::Font::openFromMemory));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::getKerning::id)
                                 .build(&sf::Font::getKerning));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::getUnderlineThickness::id)
                                 .build(&sf::Font::getUnderlineThickness));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .method(cxx::type::sf::Font::fn::openFromStream::id)
                                 .build(&sf::Font::openFromStream));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::hasGlyph::id)
                                 .build(&sf::Font::hasGlyph));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::getInfo::id)
                                 .build(&sf::Font::getInfo));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::getUnderlinePosition::id)
                                 .build(&sf::Font::getUnderlinePosition));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::getLineSpacing::id)
                                 .build(&sf::Font::getLineSpacing));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::getTexture::id)
                                 .build(&sf::Font::getTexture));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .method(cxx::type::sf::Font::fn::setSmooth::id)
                                 .build(&sf::Font::setSmooth));

        fns.push_back(rtl::type().member<sf::Font>()
                                 .methodConst(cxx::type::sf::Font::fn::isSmooth::id)
                                 .build(&sf::Font::isSmooth));
    }
}

