
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/Rect.hpp>
#include <SFML/Graphics/View.hpp>
#include <SFML/System/Angle.hpp>
#include <SFML/System/Vector2.hpp>
#include <SFML/Graphics/Transform.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs49::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::View>(cxx::type::sf::View::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::setRotation::id)
                                 .build(&sf::View::setRotation));

        fns.push_back(rtl::type().member<sf::View>()
                                 .constructor<const sf::FloatRect &>().build());

        fns.push_back(rtl::type().member<sf::View>()
                                 .constructor<sf::Vector2f, sf::Vector2f>().build());

        fns.push_back(rtl::type().member<sf::View>()
                                 .methodConst(cxx::type::sf::View::fn::getSize::id)
                                 .build(&sf::View::getSize));

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::setCenter::id)
                                 .build(&sf::View::setCenter));

        fns.push_back(rtl::type().member<sf::View>()
                                 .methodConst(cxx::type::sf::View::fn::getCenter::id)
                                 .build(&sf::View::getCenter));

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::setSize::id)
                                 .build(&sf::View::setSize));

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::setViewport::id)
                                 .build(&sf::View::setViewport));

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::setScissor::id)
                                 .build(&sf::View::setScissor));

        fns.push_back(rtl::type().member<sf::View>()
                                 .methodConst(cxx::type::sf::View::fn::getRotation::id)
                                 .build(&sf::View::getRotation));

        fns.push_back(rtl::type().member<sf::View>()
                                 .methodConst(cxx::type::sf::View::fn::getViewport::id)
                                 .build(&sf::View::getViewport));

        fns.push_back(rtl::type().member<sf::View>()
                                 .methodConst(cxx::type::sf::View::fn::getInverseTransform::id)
                                 .build(&sf::View::getInverseTransform));

        fns.push_back(rtl::type().member<sf::View>()
                                 .methodConst(cxx::type::sf::View::fn::getScissor::id)
                                 .build(&sf::View::getScissor));

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::move::id)
                                 .build(&sf::View::move));

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::rotate::id)
                                 .build(&sf::View::rotate));

        fns.push_back(rtl::type().member<sf::View>()
                                 .method(cxx::type::sf::View::fn::zoom::id)
                                 .build(&sf::View::zoom));

        fns.push_back(rtl::type().member<sf::View>()
                                 .methodConst(cxx::type::sf::View::fn::getTransform::id)
                                 .build(&sf::View::getTransform));
    }
}

