
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Network/Ftp.hpp>
#include <filesystem>
#include <xstring>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs51::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Ftp::ListingResponse>(cxx::type::sf::Ftp::ListingResponse::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Ftp::ListingResponse>()
                                 .constructor<const sf::Ftp::Response &, const std::string &>().build());
    }
}


namespace regs51::type1 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Ftp::Response>(cxx::type::sf::Ftp::Response::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .constructor<sf::Ftp::Response::Status, std::string>().build());

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .methodConst(cxx::type::sf::Ftp::Response::fn::isOk::id)
                                 .build(&sf::Ftp::Response::isOk));

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .methodConst(cxx::type::sf::Ftp::Response::fn::getStatus::id)
                                 .build(&sf::Ftp::Response::getStatus));

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .methodConst(cxx::type::sf::Ftp::Response::fn::getMessage::id)
                                 .build(&sf::Ftp::Response::getMessage));
    }
}


namespace regs51::type2 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Ftp::DirectoryResponse>(cxx::type::sf::Ftp::DirectoryResponse::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Ftp::DirectoryResponse>()
                                 .constructor<const sf::Ftp::Response &>().build());

        fns.push_back(rtl::type().member<sf::Ftp::DirectoryResponse>()
                                 .methodConst(cxx::type::sf::Ftp::DirectoryResponse::fn::getDirectory::id)
                                 .build(&sf::Ftp::DirectoryResponse::getDirectory));
    }
}

