
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/Color.hpp>
#include <SFML/System/Vector2.hpp>
#include <SFML/Graphics/Image.hpp>
#include <SFML/System/InputStream.hpp>
#include <filesystem>
#include <SFML/Graphics/Rect.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs30::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Image>(cxx::type::sf::Image::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Image>()
                                 .constructor<sf::Vector2u, sf::Color>().build());

        fns.push_back(rtl::type().member<sf::Image>()
                                 .constructor<sf::Vector2u, const unsigned char *>().build());

        fns.push_back(rtl::type().member<sf::Image>()
                                 .constructor<const std::filesystem::path &>().build());

        fns.push_back(rtl::type().member<sf::Image>()
                                 .constructor<const void *, unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::Image>()
                                 .constructor<sf::InputStream &>().build());

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::loadFromStream::id)
                                 .build(&sf::Image::loadFromStream));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method<sf::Vector2u, sf::Color>(cxx::type::sf::Image::fn::resize::id)
                                 .build(&sf::Image::resize));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method<sf::Vector2u, const unsigned char *>(cxx::type::sf::Image::fn::resize::id)
                                 .build(&sf::Image::resize));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::loadFromFile::id)
                                 .build(&sf::Image::loadFromFile));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .methodConst(cxx::type::sf::Image::fn::saveToFile::id)
                                 .build(&sf::Image::saveToFile));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::loadFromMemory::id)
                                 .build(&sf::Image::loadFromMemory));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .methodConst(cxx::type::sf::Image::fn::getSize::id)
                                 .build(&sf::Image::getSize));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::createMaskFromColor::id)
                                 .build(&sf::Image::createMaskFromColor));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::copy::id)
                                 .build(&sf::Image::copy));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::flipHorizontally::id)
                                 .build(&sf::Image::flipHorizontally));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::setPixel::id)
                                 .build(&sf::Image::setPixel));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .methodConst(cxx::type::sf::Image::fn::getPixel::id)
                                 .build(&sf::Image::getPixel));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .methodConst(cxx::type::sf::Image::fn::getPixelsPtr::id)
                                 .build(&sf::Image::getPixelsPtr));

        fns.push_back(rtl::type().member<sf::Image>()
                                 .method(cxx::type::sf::Image::fn::flipVertically::id)
                                 .build(&sf::Image::flipVertically));
    }
}

