
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/RenderStates.hpp>
#include <SFML/Graphics/Transform.hpp>
#include <SFML/Graphics/BlendMode.hpp>
#include <SFML/Graphics/StencilMode.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs32::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::RenderStates>(cxx::type::sf::RenderStates::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::RenderStates>()
                                 .constructor<const sf::Transform &>().build());

        fns.push_back(rtl::type().member<sf::RenderStates>()
                                 .constructor<const sf::BlendMode &>().build());

        fns.push_back(rtl::type().member<sf::RenderStates>()
                                 .constructor<const sf::StencilMode &>().build());
    }
}

