
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/SoundRecorder.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs20::type0 {
    void init(std::vector<rtl::Function>& fns) {

        //fns.push_back(rtl::type().record<sf::SoundRecorder>(cxx::type::sf::SoundRecorder::id)
        //                         .build());

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .methodConst(cxx::type::sf::SoundRecorder::fn::getSampleRate::id)
        //                         .build(&sf::SoundRecorder::getSampleRate));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .method(cxx::type::sf::SoundRecorder::fn::start::id)
        //                         .build(&sf::SoundRecorder::start));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .methodConst(cxx::type::sf::SoundRecorder::fn::getChannelCount::id)
        //                         .build(&sf::SoundRecorder::getChannelCount));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .methodConst(cxx::type::sf::SoundRecorder::fn::getDevice::id)
        //                         .build(&sf::SoundRecorder::getDevice));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .method(cxx::type::sf::SoundRecorder::fn::stop::id)
        //                         .build(&sf::SoundRecorder::stop));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .methodStatic(cxx::type::sf::SoundRecorder::fn::getDefaultDevice::id)
        //                         .build(&sf::SoundRecorder::getDefaultDevice));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .method(cxx::type::sf::SoundRecorder::fn::setChannelCount::id)
        //                         .build(&sf::SoundRecorder::setChannelCount));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .method(cxx::type::sf::SoundRecorder::fn::setDevice::id)
        //                         .build(&sf::SoundRecorder::setDevice));

        //fns.push_back(rtl::type().member<sf::SoundRecorder>()
        //                         .methodStatic(cxx::type::sf::SoundRecorder::fn::isAvailable::id)
        //                         .build(&sf::SoundRecorder::isAvailable));
    }
}

