
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/Transform.hpp>
#include <SFML/System/Vector2.hpp>
#include <SFML/System/Angle.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs45::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Transform>(cxx::type::sf::Transform::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Transform>()
                                 .method<sf::Angle>(cxx::type::sf::Transform::fn::rotate::id)
                                 .build(&sf::Transform::rotate));

        fns.push_back(rtl::type().member<sf::Transform>()
                                 .method<sf::Angle, sf::Vector2f>(cxx::type::sf::Transform::fn::rotate::id)
                                 .build(&sf::Transform::rotate));
    }
}

