
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/RenderTarget.hpp>
#include <SFML/Graphics/VertexBuffer.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs33::type0 {
    void init(std::vector<rtl::Function>& fns) {

        //fns.push_back(rtl::type().record<sf::RenderTarget>(cxx::type::sf::RenderTarget::id)
        //                         .build());

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst(cxx::type::sf::RenderTarget::fn::getView::id)
        //                         .build(&sf::RenderTarget::getView));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst<sf::Vector2f>(cxx::type::sf::RenderTarget::fn::mapCoordsToPixel::id)
        //                         .build(&sf::RenderTarget::mapCoordsToPixel));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst<sf::Vector2f, const sf::View &>(cxx::type::sf::RenderTarget::fn::mapCoordsToPixel::id)
        //                         .build(&sf::RenderTarget::mapCoordsToPixel));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method<sf::Color>(cxx::type::sf::RenderTarget::fn::clear::id)
        //                         .build(&sf::RenderTarget::clear));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method<sf::Color, sf::StencilValue>(cxx::type::sf::RenderTarget::fn::clear::id)
        //                         .build(&sf::RenderTarget::clear));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method(cxx::type::sf::RenderTarget::fn::setView::id)
        //                         .build(&sf::RenderTarget::setView));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method(cxx::type::sf::RenderTarget::fn::clearStencil::id)
        //                         .build(&sf::RenderTarget::clearStencil));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst(cxx::type::sf::RenderTarget::fn::getDefaultView::id)
        //                         .build(&sf::RenderTarget::getDefaultView));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method(cxx::type::sf::RenderTarget::fn::popGLStates::id)
        //                         .build(&sf::RenderTarget::popGLStates));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst(cxx::type::sf::RenderTarget::fn::getViewport::id)
        //                         .build(&sf::RenderTarget::getViewport));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst(cxx::type::sf::RenderTarget::fn::getScissor::id)
        //                         .build(&sf::RenderTarget::getScissor));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst<sf::Vector2i>(cxx::type::sf::RenderTarget::fn::mapPixelToCoords::id)
        //                         .build(&sf::RenderTarget::mapPixelToCoords));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst<sf::Vector2i, const sf::View &>(cxx::type::sf::RenderTarget::fn::mapPixelToCoords::id)
        //                         .build(&sf::RenderTarget::mapPixelToCoords));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method<const sf::Drawable &, const sf::RenderStates &>(cxx::type::sf::RenderTarget::fn::draw::id)
        //                         .build(&sf::RenderTarget::draw));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method<const sf::Vertex *, unsigned long long, sf::PrimitiveType, const sf::RenderStates &>(cxx::type::sf::RenderTarget::fn::draw::id)
        //                         .build(&sf::RenderTarget::draw));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method<const sf::VertexBuffer &, const sf::RenderStates &>(cxx::type::sf::RenderTarget::fn::draw::id)
        //                         .build(&sf::RenderTarget::draw));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method<const sf::VertexBuffer &, unsigned long long, unsigned long long, const sf::RenderStates &>(cxx::type::sf::RenderTarget::fn::draw::id)
        //                         .build(&sf::RenderTarget::draw));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .methodConst(cxx::type::sf::RenderTarget::fn::isSrgb::id)
        //                         .build(&sf::RenderTarget::isSrgb));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method(cxx::type::sf::RenderTarget::fn::setActive::id)
        //                         .build(&sf::RenderTarget::setActive));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method(cxx::type::sf::RenderTarget::fn::pushGLStates::id)
        //                         .build(&sf::RenderTarget::pushGLStates));

        //fns.push_back(rtl::type().member<sf::RenderTarget>()
        //                         .method(cxx::type::sf::RenderTarget::fn::resetGLStates::id)
        //                         .build(&sf::RenderTarget::resetGLStates));
    }
}

