
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/SoundStream.hpp>
#include <SFML/System/Time.hpp>
#include <SFML/Audio/SoundSource.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs22::type0 {
    void init(std::vector<rtl::Function>& fns) {

        //fns.push_back(rtl::type().record<sf::SoundStream>(cxx::type::sf::SoundStream::id)
        //                         .build());

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .method(cxx::type::sf::SoundStream::fn::play::id)
        //                         .build(&sf::SoundStream::play));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .methodConst(cxx::type::sf::SoundStream::fn::getChannelCount::id)
        //                         .build(&sf::SoundStream::getChannelCount));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .method(cxx::type::sf::SoundStream::fn::stop::id)
        //                         .build(&sf::SoundStream::stop));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .method(cxx::type::sf::SoundStream::fn::pause::id)
        //                         .build(&sf::SoundStream::pause));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .methodConst(cxx::type::sf::SoundStream::fn::getSampleRate::id)
        //                         .build(&sf::SoundStream::getSampleRate));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .methodConst(cxx::type::sf::SoundStream::fn::getStatus::id)
        //                         .build(&sf::SoundStream::getStatus));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .method(cxx::type::sf::SoundStream::fn::setPlayingOffset::id)
        //                         .build(&sf::SoundStream::setPlayingOffset));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .methodConst(cxx::type::sf::SoundStream::fn::getPlayingOffset::id)
        //                         .build(&sf::SoundStream::getPlayingOffset));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .method(cxx::type::sf::SoundStream::fn::setLooping::id)
        //                         .build(&sf::SoundStream::setLooping));

        //fns.push_back(rtl::type().member<sf::SoundStream>()
        //                         .methodConst(cxx::type::sf::SoundStream::fn::isLooping::id)
        //                         .build(&sf::SoundStream::isLooping));
    }
}

