
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Network/Socket.hpp>
#include <SFML/Network/SocketSelector.hpp>
#include <SFML/System/Time.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs56::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::SocketSelector>(cxx::type::sf::SocketSelector::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::SocketSelector>()
                                 .methodConst(cxx::type::sf::SocketSelector::fn::isReady::id)
                                 .build(&sf::SocketSelector::isReady));

        fns.push_back(rtl::type().member<sf::SocketSelector>()
                                 .method(cxx::type::sf::SocketSelector::fn::add::id)
                                 .build(&sf::SocketSelector::add));

        fns.push_back(rtl::type().member<sf::SocketSelector>()
                                 .method(cxx::type::sf::SocketSelector::fn::remove::id)
                                 .build(&sf::SocketSelector::remove));

        fns.push_back(rtl::type().member<sf::SocketSelector>()
                                 .method(cxx::type::sf::SocketSelector::fn::clear::id)
                                 .build(&sf::SocketSelector::clear));

        fns.push_back(rtl::type().member<sf::SocketSelector>()
                                 .method(cxx::type::sf::SocketSelector::fn::wait::id)
                                 .build(&sf::SocketSelector::wait));
    }
}

