
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/Listener.hpp>
#include <SFML/System/Vector3.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs3::fn {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::getDirection::id)
                                 .build(&sf::Listener::getDirection));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::getGlobalVolume::id)
                                 .build(&sf::Listener::getGlobalVolume));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::setCone::id)
                                 .build(&sf::Listener::setCone));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::setVelocity::id)
                                 .build(&sf::Listener::setVelocity));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::setPosition::id)
                                 .build(&sf::Listener::setPosition));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::getPosition::id)
                                 .build(&sf::Listener::getPosition));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::getVelocity::id)
                                 .build(&sf::Listener::getVelocity));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::setDirection::id)
                                 .build(&sf::Listener::setDirection));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::getCone::id)
                                 .build(&sf::Listener::getCone));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::setUpVector::id)
                                 .build(&sf::Listener::setUpVector));

        fns.push_back(rtl::type().function(cxx::fn::sf::Listener::getUpVector::id)
                                 .build(&sf::Listener::getUpVector));
    }
}

