
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/System/Time.hpp>
#include <SFML/System/Clock.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs61::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Clock>(cxx::type::sf::Clock::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Clock>()
                                 .method(cxx::type::sf::Clock::fn::restart::id)
                                 .build(&sf::Clock::restart));

        fns.push_back(rtl::type().member<sf::Clock>()
                                 .methodConst(cxx::type::sf::Clock::fn::isRunning::id)
                                 .build(&sf::Clock::isRunning));

        fns.push_back(rtl::type().member<sf::Clock>()
                                 .methodConst(cxx::type::sf::Clock::fn::getElapsedTime::id)
                                 .build(&sf::Clock::getElapsedTime));

        fns.push_back(rtl::type().member<sf::Clock>()
                                 .method(cxx::type::sf::Clock::fn::start::id)
                                 .build(&sf::Clock::start));

        fns.push_back(rtl::type().member<sf::Clock>()
                                 .method(cxx::type::sf::Clock::fn::stop::id)
                                 .build(&sf::Clock::stop));

        fns.push_back(rtl::type().member<sf::Clock>()
                                 .method(cxx::type::sf::Clock::fn::reset::id)
                                 .build(&sf::Clock::reset));
    }
}

