
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/RenderTexture.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs34::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::RenderTexture>(cxx::type::sf::RenderTexture::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .constructor<sf::Vector2u, const sf::ContextSettings &>().build());

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .method(cxx::type::sf::RenderTexture::fn::setRepeated::id)
                                 .build(&sf::RenderTexture::setRepeated));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .method(cxx::type::sf::RenderTexture::fn::resize::id)
                                 .build(&sf::RenderTexture::resize));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .method(cxx::type::sf::RenderTexture::fn::setSmooth::id)
                                 .build(&sf::RenderTexture::setSmooth));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .methodConst(cxx::type::sf::RenderTexture::fn::isRepeated::id)
                                 .build(&sf::RenderTexture::isRepeated));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .methodStatic(cxx::type::sf::RenderTexture::fn::getMaximumAntiAliasingLevel::id)
                                 .build(&sf::RenderTexture::getMaximumAntiAliasingLevel));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .methodConst(cxx::type::sf::RenderTexture::fn::isSmooth::id)
                                 .build(&sf::RenderTexture::isSmooth));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .method(cxx::type::sf::RenderTexture::fn::generateMipmap::id)
                                 .build(&sf::RenderTexture::generateMipmap));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .method(cxx::type::sf::RenderTexture::fn::setActive::id)
                                 .build(&sf::RenderTexture::setActive));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .method(cxx::type::sf::RenderTexture::fn::display::id)
                                 .build(&sf::RenderTexture::display));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .methodConst(cxx::type::sf::RenderTexture::fn::getSize::id)
                                 .build(&sf::RenderTexture::getSize));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .methodConst(cxx::type::sf::RenderTexture::fn::isSrgb::id)
                                 .build(&sf::RenderTexture::isSrgb));

        fns.push_back(rtl::type().member<sf::RenderTexture>()
                                 .methodConst(cxx::type::sf::RenderTexture::fn::getTexture::id)
                                 .build(&sf::RenderTexture::getTexture));
    }
}

