
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/InputSoundFile.hpp>
#include <SFML/System/FileInputStream.hpp>
#include <SFML/System/Time.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs2::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::InputSoundFile>(cxx::type::sf::InputSoundFile::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .methodConst(cxx::type::sf::InputSoundFile::fn::getChannelCount::id)
                                 .build(&sf::InputSoundFile::getChannelCount));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .constructor<const std::filesystem::path &>().build());

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .constructor<const void *, unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .constructor<sf::InputStream &>().build());

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .method(cxx::type::sf::InputSoundFile::fn::openFromFile::id)
                                 .build(&sf::InputSoundFile::openFromFile));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .methodConst(cxx::type::sf::InputSoundFile::fn::getSampleRate::id)
                                 .build(&sf::InputSoundFile::getSampleRate));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .method(cxx::type::sf::InputSoundFile::fn::openFromMemory::id)
                                 .build(&sf::InputSoundFile::openFromMemory));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .method(cxx::type::sf::InputSoundFile::fn::openFromStream::id)
                                 .build(&sf::InputSoundFile::openFromStream));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .methodConst(cxx::type::sf::InputSoundFile::fn::getSampleCount::id)
                                 .build(&sf::InputSoundFile::getSampleCount));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .methodConst(cxx::type::sf::InputSoundFile::fn::getDuration::id)
                                 .build(&sf::InputSoundFile::getDuration));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .methodConst(cxx::type::sf::InputSoundFile::fn::getTimeOffset::id)
                                 .build(&sf::InputSoundFile::getTimeOffset));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .methodConst(cxx::type::sf::InputSoundFile::fn::getSampleOffset::id)
                                 .build(&sf::InputSoundFile::getSampleOffset));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .method<unsigned long long>(cxx::type::sf::InputSoundFile::fn::seek::id)
                                 .build(&sf::InputSoundFile::seek));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .method<sf::Time>(cxx::type::sf::InputSoundFile::fn::seek::id)
                                 .build(&sf::InputSoundFile::seek));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .method(cxx::type::sf::InputSoundFile::fn::read::id)
                                 .build(&sf::InputSoundFile::read));

        fns.push_back(rtl::type().member<sf::InputSoundFile>()
                                 .method(cxx::type::sf::InputSoundFile::fn::close::id)
                                 .build(&sf::InputSoundFile::close));
    }
}

