
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/Color.hpp>
#include <SFML/Graphics/Texture.hpp>
#include <SFML/Graphics/Sprite.hpp>
#include <SFML/Graphics/Rect.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs40::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Sprite>(cxx::type::sf::Sprite::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .constructor<const sf::Texture &>().build());

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .constructor<const sf::Texture &, const sf::IntRect &>().build());

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .method(cxx::type::sf::Sprite::fn::setColor::id)
                                 .build(&sf::Sprite::setColor));

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .method<const sf::Texture&, bool>(cxx::type::sf::Sprite::fn::setTexture::id)
                                 .build(&sf::Sprite::setTexture));

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .method(cxx::type::sf::Sprite::fn::setTextureRect::id)
                                 .build(&sf::Sprite::setTextureRect));

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .methodConst(cxx::type::sf::Sprite::fn::getColor::id)
                                 .build(&sf::Sprite::getColor));

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .methodConst(cxx::type::sf::Sprite::fn::getTexture::id)
                                 .build(&sf::Sprite::getTexture));

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .methodConst(cxx::type::sf::Sprite::fn::getTextureRect::id)
                                 .build(&sf::Sprite::getTextureRect));

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .methodConst(cxx::type::sf::Sprite::fn::getLocalBounds::id)
                                 .build(&sf::Sprite::getLocalBounds));

        fns.push_back(rtl::type().member<sf::Sprite>()
                                 .methodConst(cxx::type::sf::Sprite::fn::getGlobalBounds::id)
                                 .build(&sf::Sprite::getGlobalBounds));
    }
}

