
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <xstring>
#include <SFML/Network/Http.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs52::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Http::Request>(cxx::type::sf::Http::Request::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Http::Request>()
                                 .method(cxx::type::sf::Http::Request::fn::setHttpVersion::id)
                                 .build(&sf::Http::Request::setHttpVersion));

        fns.push_back(rtl::type().member<sf::Http::Request>()
                                 .method(cxx::type::sf::Http::Request::fn::setField::id)
                                 .build(&sf::Http::Request::setField));

        fns.push_back(rtl::type().member<sf::Http::Request>()
                                 .method(cxx::type::sf::Http::Request::fn::setMethod::id)
                                 .build(&sf::Http::Request::setMethod));

        fns.push_back(rtl::type().member<sf::Http::Request>()
                                 .method(cxx::type::sf::Http::Request::fn::setBody::id)
                                 .build(&sf::Http::Request::setBody));

        fns.push_back(rtl::type().member<sf::Http::Request>()
                                 .method(cxx::type::sf::Http::Request::fn::setUri::id)
                                 .build(&sf::Http::Request::setUri));
    }
}


namespace regs52::type1 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Http::Response>(cxx::type::sf::Http::Response::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Http::Response>()
                                 .methodConst(cxx::type::sf::Http::Response::fn::getStatus::id)
                                 .build(&sf::Http::Response::getStatus));

        fns.push_back(rtl::type().member<sf::Http::Response>()
                                 .methodConst(cxx::type::sf::Http::Response::fn::getField::id)
                                 .build(&sf::Http::Response::getField));

        fns.push_back(rtl::type().member<sf::Http::Response>()
                                 .methodConst(cxx::type::sf::Http::Response::fn::getMajorHttpVersion::id)
                                 .build(&sf::Http::Response::getMajorHttpVersion));

        fns.push_back(rtl::type().member<sf::Http::Response>()
                                 .methodConst(cxx::type::sf::Http::Response::fn::getMinorHttpVersion::id)
                                 .build(&sf::Http::Response::getMinorHttpVersion));

        fns.push_back(rtl::type().member<sf::Http::Response>()
                                 .methodConst(cxx::type::sf::Http::Response::fn::getBody::id)
                                 .build(&sf::Http::Response::getBody));
    }
}

