
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Network/Packet.hpp>
#include <SFML/Network/UdpSocket.hpp>
#include <SFML/Network/Socket.hpp>
#include <SFML/Network/IpAddress.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs59::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::UdpSocket>(cxx::type::sf::UdpSocket::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::UdpSocket>()
                                 .method(cxx::type::sf::UdpSocket::fn::unbind::id)
                                 .build(&sf::UdpSocket::unbind));

        fns.push_back(rtl::type().member<sf::UdpSocket>()
                                 .methodConst(cxx::type::sf::UdpSocket::fn::getLocalPort::id)
                                 .build(&sf::UdpSocket::getLocalPort));

        fns.push_back(rtl::type().member<sf::UdpSocket>()
                                 .method(cxx::type::sf::UdpSocket::fn::bind::id)
                                 .build(&sf::UdpSocket::bind));

        fns.push_back(rtl::type().member<sf::UdpSocket>()
                                 .method<const void *, unsigned long long, sf::IpAddress, unsigned short>(cxx::type::sf::UdpSocket::fn::send::id)
                                 .build(&sf::UdpSocket::send));

        fns.push_back(rtl::type().member<sf::UdpSocket>()
                                 .method<sf::Packet &, sf::IpAddress, unsigned short>(cxx::type::sf::UdpSocket::fn::send::id)
                                 .build(&sf::UdpSocket::send));
    }
}

