
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Window/VideoMode.hpp>
#include <SFML/System/Vector2.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs83::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::VideoMode>(cxx::type::sf::VideoMode::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::VideoMode>()
                                 .constructor<sf::Vector2u, unsigned int>().build());

        fns.push_back(rtl::type().member<sf::VideoMode>()
                                 .methodStatic(cxx::type::sf::VideoMode::fn::getDesktopMode::id)
                                 .build(&sf::VideoMode::getDesktopMode));

        fns.push_back(rtl::type().member<sf::VideoMode>()
                                 .methodConst(cxx::type::sf::VideoMode::fn::isValid::id)
                                 .build(&sf::VideoMode::isValid));
    }
}

