
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/Shader.hpp>
#include <SFML/System/InputStream.hpp>
#include <SFML/Graphics/Texture.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs38::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Shader>(cxx::type::sf::Shader::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, float>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, sf::Glsl::Vec2>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Vec3 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Vec4 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, int>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, sf::Glsl::Ivec2>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Ivec3 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Ivec4 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, bool>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, sf::Glsl::Bvec2>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Bvec3 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Bvec4 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Mat3 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Mat4 &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Texture &>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, sf::Shader::CurrentTextureType>(cxx::type::sf::Shader::fn::setUniform::id)
                                 .build(&sf::Shader::setUniform));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<const std::filesystem::path &, sf::Shader::Type>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<const std::filesystem::path &, const std::filesystem::path &>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<const std::filesystem::path &, const std::filesystem::path &, const std::filesystem::path &>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<std::string_view, sf::Shader::Type>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<std::string_view, std::string_view>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<std::string_view, std::string_view, std::string_view>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<sf::InputStream &, sf::Shader::Type>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<sf::InputStream &, sf::InputStream &>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .constructor<sf::InputStream &, sf::InputStream &, sf::InputStream &>().build());

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::filesystem::path &, sf::Shader::Type>(cxx::type::sf::Shader::fn::loadFromFile::id)
                                 .build(&sf::Shader::loadFromFile));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::filesystem::path &, const std::filesystem::path &>(cxx::type::sf::Shader::fn::loadFromFile::id)
                                 .build(&sf::Shader::loadFromFile));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::filesystem::path &, const std::filesystem::path &, const std::filesystem::path &>(cxx::type::sf::Shader::fn::loadFromFile::id)
                                 .build(&sf::Shader::loadFromFile));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .methodConst(cxx::type::sf::Shader::fn::getNativeHandle::id)
                                 .build(&sf::Shader::getNativeHandle));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<std::string_view, sf::Shader::Type>(cxx::type::sf::Shader::fn::loadFromMemory::id)
                                 .build(&sf::Shader::loadFromMemory));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<std::string_view, std::string_view>(cxx::type::sf::Shader::fn::loadFromMemory::id)
                                 .build(&sf::Shader::loadFromMemory));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<std::string_view, std::string_view, std::string_view>(cxx::type::sf::Shader::fn::loadFromMemory::id)
                                 .build(&sf::Shader::loadFromMemory));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<sf::InputStream &, sf::Shader::Type>(cxx::type::sf::Shader::fn::loadFromStream::id)
                                 .build(&sf::Shader::loadFromStream));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<sf::InputStream &, sf::InputStream &>(cxx::type::sf::Shader::fn::loadFromStream::id)
                                 .build(&sf::Shader::loadFromStream));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<sf::InputStream &, sf::InputStream &, sf::InputStream &>(cxx::type::sf::Shader::fn::loadFromStream::id)
                                 .build(&sf::Shader::loadFromStream));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .methodStatic(cxx::type::sf::Shader::fn::bind::id)
                                 .build(&sf::Shader::bind));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const float *, unsigned long long>(cxx::type::sf::Shader::fn::setUniformArray::id)
                                 .build(&sf::Shader::setUniformArray));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Vec2 *, unsigned long long>(cxx::type::sf::Shader::fn::setUniformArray::id)
                                 .build(&sf::Shader::setUniformArray));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Vec3 *, unsigned long long>(cxx::type::sf::Shader::fn::setUniformArray::id)
                                 .build(&sf::Shader::setUniformArray));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Vec4 *, unsigned long long>(cxx::type::sf::Shader::fn::setUniformArray::id)
                                 .build(&sf::Shader::setUniformArray));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Mat3 *, unsigned long long>(cxx::type::sf::Shader::fn::setUniformArray::id)
                                 .build(&sf::Shader::setUniformArray));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .method<const std::string &, const sf::Glsl::Mat4 *, unsigned long long>(cxx::type::sf::Shader::fn::setUniformArray::id)
                                 .build(&sf::Shader::setUniformArray));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .methodStatic(cxx::type::sf::Shader::fn::isAvailable::id)
                                 .build(&sf::Shader::isAvailable));

        fns.push_back(rtl::type().member<sf::Shader>()
                                 .methodStatic(cxx::type::sf::Shader::fn::isGeometryAvailable::id)
                                 .build(&sf::Shader::isGeometryAvailable));
    }
}

