
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Window/Window.hpp>
#include <SFML/Window/VideoMode.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs94::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Window>(cxx::type::sf::Window::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method(cxx::type::sf::Window::fn::display::id)
                                 .build(&sf::Window::display));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .methodConst(cxx::type::sf::Window::fn::setActive::id)
                                 .build(&sf::Window::setActive));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method<sf::VideoMode, const sf::String &, unsigned int, sf::State>(cxx::type::sf::Window::fn::create::id)
                                 .build(&sf::Window::create));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method<sf::VideoMode, const sf::String &, unsigned int, sf::State, const sf::ContextSettings &>(cxx::type::sf::Window::fn::create::id)
                                 .build(&sf::Window::create));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method<sf::VideoMode, const sf::String &, sf::State>(cxx::type::sf::Window::fn::create::id)
                                 .build(&sf::Window::create));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method<sf::VideoMode, const sf::String &, sf::State, const sf::ContextSettings &>(cxx::type::sf::Window::fn::create::id)
                                 .build(&sf::Window::create));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .constructor<sf::VideoMode, const sf::String &, unsigned int, sf::State, const sf::ContextSettings &>().build());

        fns.push_back(rtl::type().member<sf::Window>()
                                 .constructor<sf::VideoMode, const sf::String &, sf::State, const sf::ContextSettings &>().build());

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method(cxx::type::sf::Window::fn::close::id)
                                 .build(&sf::Window::close));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .methodConst(cxx::type::sf::Window::fn::getSettings::id)
                                 .build(&sf::Window::getSettings));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method(cxx::type::sf::Window::fn::setVerticalSyncEnabled::id)
                                 .build(&sf::Window::setVerticalSyncEnabled));

        fns.push_back(rtl::type().member<sf::Window>()
                                 .method(cxx::type::sf::Window::fn::setFramerateLimit::id)
                                 .build(&sf::Window::setFramerateLimit));
    }
}

