
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/System/Time.hpp>
#include <SFML/Network/Ftp.hpp>
#include <SFML/Network/IpAddress.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs51::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Ftp::ListingResponse>(cxx::type::sf::Ftp::ListingResponse::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Ftp::ListingResponse>()
                                 .constructor<const sf::Ftp::Response &, const std::string &>().build());
    }
}


namespace regs51::type1 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Ftp::Response>(cxx::type::sf::Ftp::Response::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .constructor<sf::Ftp::Response::Status, std::string>().build());

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .methodConst(cxx::type::sf::Ftp::Response::fn::isOk::id)
                                 .build(&sf::Ftp::Response::isOk));

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .methodConst(cxx::type::sf::Ftp::Response::fn::getStatus::id)
                                 .build(&sf::Ftp::Response::getStatus));

        fns.push_back(rtl::type().member<sf::Ftp::Response>()
                                 .methodConst(cxx::type::sf::Ftp::Response::fn::getMessage::id)
                                 .build(&sf::Ftp::Response::getMessage));
    }
}


namespace regs51::type2 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Ftp::DirectoryResponse>(cxx::type::sf::Ftp::DirectoryResponse::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Ftp::DirectoryResponse>()
                                 .constructor<const sf::Ftp::Response &>().build());

        fns.push_back(rtl::type().member<sf::Ftp::DirectoryResponse>()
                                 .methodConst(cxx::type::sf::Ftp::DirectoryResponse::fn::getDirectory::id)
                                 .build(&sf::Ftp::DirectoryResponse::getDirectory));
    }
}


namespace regs51::type3 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Ftp>(cxx::type::sf::Ftp::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::keepAlive::id)
                                 .build(&sf::Ftp::keepAlive));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::connect::id)
                                 .build(&sf::Ftp::connect));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method<void>(cxx::type::sf::Ftp::fn::login::id)
                                 .build(&sf::Ftp::login));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method<const std::string &, const std::string &>(cxx::type::sf::Ftp::fn::login::id)
                                 .build(&sf::Ftp::login));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::disconnect::id)
                                 .build(&sf::Ftp::disconnect));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::getWorkingDirectory::id)
                                 .build(&sf::Ftp::getWorkingDirectory));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::getDirectoryListing::id)
                                 .build(&sf::Ftp::getDirectoryListing));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::parentDirectory::id)
                                 .build(&sf::Ftp::parentDirectory));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::createDirectory::id)
                                 .build(&sf::Ftp::createDirectory));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::changeDirectory::id)
                                 .build(&sf::Ftp::changeDirectory));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::deleteDirectory::id)
                                 .build(&sf::Ftp::deleteDirectory));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::renameFile::id)
                                 .build(&sf::Ftp::renameFile));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::sendCommand::id)
                                 .build(&sf::Ftp::sendCommand));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::deleteFile::id)
                                 .build(&sf::Ftp::deleteFile));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::download::id)
                                 .build(&sf::Ftp::download));

        fns.push_back(rtl::type().member<sf::Ftp>()
                                 .method(cxx::type::sf::Ftp::fn::upload::id)
                                 .build(&sf::Ftp::upload));
    }
}

