
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/CircleShape.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs24::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::CircleShape>(cxx::type::sf::CircleShape::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::CircleShape>()
                                 .methodConst(cxx::type::sf::CircleShape::fn::getGeometricCenter::id)
                                 .build(&sf::CircleShape::getGeometricCenter));

        fns.push_back(rtl::type().member<sf::CircleShape>()
                                 .methodConst(cxx::type::sf::CircleShape::fn::getRadius::id)
                                 .build(&sf::CircleShape::getRadius));

        fns.push_back(rtl::type().member<sf::CircleShape>()
                                 .constructor<float, unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::CircleShape>()
                                 .method(cxx::type::sf::CircleShape::fn::setRadius::id)
                                 .build(&sf::CircleShape::setRadius));

        fns.push_back(rtl::type().member<sf::CircleShape>()
                                 .method(cxx::type::sf::CircleShape::fn::setPointCount::id)
                                 .build(&sf::CircleShape::setPointCount));

        fns.push_back(rtl::type().member<sf::CircleShape>()
                                 .methodConst(cxx::type::sf::CircleShape::fn::getPointCount::id)
                                 .build(&sf::CircleShape::getPointCount));

        fns.push_back(rtl::type().member<sf::CircleShape>()
                                 .methodConst(cxx::type::sf::CircleShape::fn::getPoint::id)
                                 .build(&sf::CircleShape::getPoint));
    }
}

