
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/PrimitiveType.hpp>
#include <SFML/Graphics/VertexArray.hpp>
#include <SFML/Graphics/Rect.hpp>
#include <SFML/Graphics/Vertex.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs47::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::VertexArray>(cxx::type::sf::VertexArray::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .constructor<sf::PrimitiveType, unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .method(cxx::type::sf::VertexArray::fn::setPrimitiveType::id)
                                 .build(&sf::VertexArray::setPrimitiveType));

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .methodConst(cxx::type::sf::VertexArray::fn::getVertexCount::id)
                                 .build(&sf::VertexArray::getVertexCount));

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .methodConst(cxx::type::sf::VertexArray::fn::getBounds::id)
                                 .build(&sf::VertexArray::getBounds));

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .method(cxx::type::sf::VertexArray::fn::clear::id)
                                 .build(&sf::VertexArray::clear));

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .method(cxx::type::sf::VertexArray::fn::append::id)
                                 .build(&sf::VertexArray::append));

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .method(cxx::type::sf::VertexArray::fn::resize::id)
                                 .build(&sf::VertexArray::resize));

        fns.push_back(rtl::type().member<sf::VertexArray>()
                                 .methodConst(cxx::type::sf::VertexArray::fn::getPrimitiveType::id)
                                 .build(&sf::VertexArray::getPrimitiveType));
    }
}

