
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Network/IpAddress.hpp>
#include <xstring>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs53::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::IpAddress>(cxx::type::sf::IpAddress::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::IpAddress>()
                                 .methodConst(cxx::type::sf::IpAddress::fn::toString::id)
                                 .build(&sf::IpAddress::toString));

        fns.push_back(rtl::type().member<sf::IpAddress>()
                                 .constructor<unsigned char, unsigned char, unsigned char, unsigned char>().build());

        fns.push_back(rtl::type().member<sf::IpAddress>()
                                 .constructor<unsigned int>().build());

        fns.push_back(rtl::type().member<sf::IpAddress>()
                                 .methodConst(cxx::type::sf::IpAddress::fn::toInteger::id)
                                 .build(&sf::IpAddress::toInteger));
    }
}

