
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/System/Vector2.hpp>
#include <SFML/Graphics/Color.hpp>
#include <SFML/Graphics/Texture.hpp>
#include <SFML/Graphics/Shape.hpp>
#include <SFML/Graphics/Rect.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs39::type0 {
    void init(std::vector<rtl::Function>& fns) {

        //fns.push_back(rtl::type().record<sf::Shape>(cxx::type::sf::Shape::id)
        //                         .build());

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getOutlineColor::id)
        //                         .build(&sf::Shape::getOutlineColor));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .method(cxx::type::sf::Shape::fn::setTexture::id)
        //                         .build(&sf::Shape::setTexture));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .method(cxx::type::sf::Shape::fn::setOutlineColor::id)
        //                         .build(&sf::Shape::setOutlineColor));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getTexture::id)
        //                         .build(&sf::Shape::getTexture));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .method(cxx::type::sf::Shape::fn::setTextureRect::id)
        //                         .build(&sf::Shape::setTextureRect));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getTextureRect::id)
        //                         .build(&sf::Shape::getTextureRect));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .method(cxx::type::sf::Shape::fn::setFillColor::id)
        //                         .build(&sf::Shape::setFillColor));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getFillColor::id)
        //                         .build(&sf::Shape::getFillColor));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .method(cxx::type::sf::Shape::fn::setOutlineThickness::id)
        //                         .build(&sf::Shape::setOutlineThickness));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getOutlineThickness::id)
        //                         .build(&sf::Shape::getOutlineThickness));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getGeometricCenter::id)
        //                         .build(&sf::Shape::getGeometricCenter));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getLocalBounds::id)
        //                         .build(&sf::Shape::getLocalBounds));

        //fns.push_back(rtl::type().member<sf::Shape>()
        //                         .methodConst(cxx::type::sf::Shape::fn::getGlobalBounds::id)
        //                         .build(&sf::Shape::getGlobalBounds));
    }
}

