
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/Music.hpp>
#include <SFML/System/Time.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs6::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Music>(cxx::type::sf::Music::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Music>()
                                 .constructor<const std::filesystem::path &>().build());

        fns.push_back(rtl::type().member<sf::Music>()
                                 .constructor<const void *, unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::Music>()
                                 .method(cxx::type::sf::Music::fn::openFromFile::id)
                                 .build(&sf::Music::openFromFile));

        fns.push_back(rtl::type().member<sf::Music>()
                                 .method(cxx::type::sf::Music::fn::setLoopPoints::id)
                                 .build(&sf::Music::setLoopPoints));

        fns.push_back(rtl::type().member<sf::Music>()
                                 .method(cxx::type::sf::Music::fn::openFromMemory::id)
                                 .build(&sf::Music::openFromMemory));

        fns.push_back(rtl::type().member<sf::Music>()
                                 .methodConst(cxx::type::sf::Music::fn::getDuration::id)
                                 .build(&sf::Music::getDuration));

        fns.push_back(rtl::type().member<sf::Music>()
                                 .methodConst(cxx::type::sf::Music::fn::getLoopPoints::id)
                                 .build(&sf::Music::getLoopPoints));
    }
}

