
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Network/Packet.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs54::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Packet>(cxx::type::sf::Packet::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Packet>()
                                 .method(cxx::type::sf::Packet::fn::append::id)
                                 .build(&sf::Packet::append));

        fns.push_back(rtl::type().member<sf::Packet>()
                                 .methodConst(cxx::type::sf::Packet::fn::getReadPosition::id)
                                 .build(&sf::Packet::getReadPosition));

        fns.push_back(rtl::type().member<sf::Packet>()
                                 .method(cxx::type::sf::Packet::fn::clear::id)
                                 .build(&sf::Packet::clear));

        fns.push_back(rtl::type().member<sf::Packet>()
                                 .methodConst(cxx::type::sf::Packet::fn::endOfPacket::id)
                                 .build(&sf::Packet::endOfPacket));

        fns.push_back(rtl::type().member<sf::Packet>()
                                 .methodConst(cxx::type::sf::Packet::fn::getData::id)
                                 .build(&sf::Packet::getData));

        fns.push_back(rtl::type().member<sf::Packet>()
                                 .methodConst(cxx::type::sf::Packet::fn::getDataSize::id)
                                 .build(&sf::Packet::getDataSize));
    }
}

