
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Window/Keyboard.hpp>
#include <SFML/System/String.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs78::fn {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().function(cxx::fn::sf::Keyboard::localize::id)
                                 .build(&sf::Keyboard::localize));

        fns.push_back(rtl::type().function<sf::Keyboard::Key>(cxx::fn::sf::Keyboard::isKeyPressed::id)
                                 .build(&sf::Keyboard::isKeyPressed));

        fns.push_back(rtl::type().function<sf::Keyboard::Scan>(cxx::fn::sf::Keyboard::isKeyPressed::id)
                                 .build(&sf::Keyboard::isKeyPressed));

        fns.push_back(rtl::type().function(cxx::fn::sf::Keyboard::delocalize::id)
                                 .build(&sf::Keyboard::delocalize));

        fns.push_back(rtl::type().function(cxx::fn::sf::Keyboard::getDescription::id)
                                 .build(&sf::Keyboard::getDescription));
    }
}

