
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Network/Packet.hpp>
#include <SFML/Network/TcpSocket.hpp>
#include <SFML/Network/Socket.hpp>
#include <SFML/Network/IpAddress.hpp>
#include <SFML/System/Time.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs58::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::TcpSocket>(cxx::type::sf::TcpSocket::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .method(cxx::type::sf::TcpSocket::fn::connect::id)
                                 .build(&sf::TcpSocket::connect));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .methodConst(cxx::type::sf::TcpSocket::fn::getLocalPort::id)
                                 .build(&sf::TcpSocket::getLocalPort));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .methodConst(cxx::type::sf::TcpSocket::fn::getRemotePort::id)
                                 .build(&sf::TcpSocket::getRemotePort));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .method(cxx::type::sf::TcpSocket::fn::disconnect::id)
                                 .build(&sf::TcpSocket::disconnect));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .method<const void *, unsigned long long>(cxx::type::sf::TcpSocket::fn::send::id)
                                 .build(&sf::TcpSocket::send));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .method<const void *, unsigned long long, unsigned long long &>(cxx::type::sf::TcpSocket::fn::send::id)
                                 .build(&sf::TcpSocket::send));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .method<sf::Packet &>(cxx::type::sf::TcpSocket::fn::send::id)
                                 .build(&sf::TcpSocket::send));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .method<void *, unsigned long long, unsigned long long &>(cxx::type::sf::TcpSocket::fn::receive::id)
                                 .build(&sf::TcpSocket::receive));

        fns.push_back(rtl::type().member<sf::TcpSocket>()
                                 .method<sf::Packet &>(cxx::type::sf::TcpSocket::fn::receive::id)
                                 .build(&sf::TcpSocket::receive));
    }
}

