
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/ConvexShape.hpp>
#include <SFML/System/Vector2.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs25::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::ConvexShape>(cxx::type::sf::ConvexShape::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::ConvexShape>()
                                 .constructor<unsigned long long>().build());

        fns.push_back(rtl::type().member<sf::ConvexShape>()
                                 .method(cxx::type::sf::ConvexShape::fn::setPointCount::id)
                                 .build(&sf::ConvexShape::setPointCount));

        fns.push_back(rtl::type().member<sf::ConvexShape>()
                                 .methodConst(cxx::type::sf::ConvexShape::fn::getPointCount::id)
                                 .build(&sf::ConvexShape::getPointCount));

        fns.push_back(rtl::type().member<sf::ConvexShape>()
                                 .method(cxx::type::sf::ConvexShape::fn::setPoint::id)
                                 .build(&sf::ConvexShape::setPoint));

        fns.push_back(rtl::type().member<sf::ConvexShape>()
                                 .methodConst(cxx::type::sf::ConvexShape::fn::getPoint::id)
                                 .build(&sf::ConvexShape::getPoint));
    }
}

