
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/Graphics/Image.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs37::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::RenderWindow>(cxx::type::sf::RenderWindow::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::RenderWindow>()
                                 .method(cxx::type::sf::RenderWindow::fn::setActive::id)
                                 .build(&sf::RenderWindow::setActive));

        fns.push_back(rtl::type().member<sf::RenderWindow>()
                                 .methodConst(cxx::type::sf::RenderWindow::fn::isSrgb::id)
                                 .build(&sf::RenderWindow::isSrgb));

        fns.push_back(rtl::type().member<sf::RenderWindow>()
                                 .constructor<sf::VideoMode, const sf::String &, unsigned int, sf::State, const sf::ContextSettings &>().build());

        fns.push_back(rtl::type().member<sf::RenderWindow>()
                                 .constructor<sf::VideoMode, const sf::String &, sf::State, const sf::ContextSettings &>().build());

        fns.push_back(rtl::type().member<sf::RenderWindow>()
                                 .methodConst(cxx::type::sf::RenderWindow::fn::getSize::id)
                                 .build(&sf::RenderWindow::getSize));

        fns.push_back(rtl::type().member<sf::RenderWindow>()
                                 .method<const sf::Image&>(cxx::type::sf::RenderWindow::fn::setIcon::id)
                                 .build(&sf::RenderWindow::setIcon));
    }
}

