
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/SoundSource.hpp>
#include <SFML/System/Vector3.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs21::type0 {
    void init(std::vector<rtl::Function>& fns) {

        //fns.push_back(rtl::type().record<sf::SoundSource>(cxx::type::sf::SoundSource::id)
        //                         .build());

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setPitch::id)
        //                         .build(&sf::SoundSource::setPitch));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::isSpatializationEnabled::id)
        //                         .build(&sf::SoundSource::isSpatializationEnabled));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setPan::id)
        //                         .build(&sf::SoundSource::setPan));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setVolume::id)
        //                         .build(&sf::SoundSource::setVolume));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setVelocity::id)
        //                         .build(&sf::SoundSource::setVelocity));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setDirectionalAttenuationFactor::id)
        //                         .build(&sf::SoundSource::setDirectionalAttenuationFactor));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setSpatializationEnabled::id)
        //                         .build(&sf::SoundSource::setSpatializationEnabled));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setCone::id)
        //                         .build(&sf::SoundSource::setCone));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setDirection::id)
        //                         .build(&sf::SoundSource::setDirection));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setPosition::id)
        //                         .build(&sf::SoundSource::setPosition));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setDopplerFactor::id)
        //                         .build(&sf::SoundSource::setDopplerFactor));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setRelativeToListener::id)
        //                         .build(&sf::SoundSource::setRelativeToListener));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setMinDistance::id)
        //                         .build(&sf::SoundSource::setMinDistance));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getPosition::id)
        //                         .build(&sf::SoundSource::getPosition));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setMaxGain::id)
        //                         .build(&sf::SoundSource::setMaxGain));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setMaxDistance::id)
        //                         .build(&sf::SoundSource::setMaxDistance));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getDopplerFactor::id)
        //                         .build(&sf::SoundSource::getDopplerFactor));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setMinGain::id)
        //                         .build(&sf::SoundSource::setMinGain));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .method(cxx::type::sf::SoundSource::fn::setAttenuation::id)
        //                         .build(&sf::SoundSource::setAttenuation));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getPitch::id)
        //                         .build(&sf::SoundSource::getPitch));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getPan::id)
        //                         .build(&sf::SoundSource::getPan));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getVolume::id)
        //                         .build(&sf::SoundSource::getVolume));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getCone::id)
        //                         .build(&sf::SoundSource::getCone));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getDirection::id)
        //                         .build(&sf::SoundSource::getDirection));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getVelocity::id)
        //                         .build(&sf::SoundSource::getVelocity));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getDirectionalAttenuationFactor::id)
        //                         .build(&sf::SoundSource::getDirectionalAttenuationFactor));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::isRelativeToListener::id)
        //                         .build(&sf::SoundSource::isRelativeToListener));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getMinDistance::id)
        //                         .build(&sf::SoundSource::getMinDistance));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getMaxDistance::id)
        //                         .build(&sf::SoundSource::getMaxDistance));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getMinGain::id)
        //                         .build(&sf::SoundSource::getMinGain));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getMaxGain::id)
        //                         .build(&sf::SoundSource::getMaxGain));

        //fns.push_back(rtl::type().member<sf::SoundSource>()
        //                         .methodConst(cxx::type::sf::SoundSource::fn::getAttenuation::id)
        //                         .build(&sf::SoundSource::getAttenuation));
    }
}

