
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/RectangleShape.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs31::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::RectangleShape>(cxx::type::sf::RectangleShape::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::RectangleShape>()
                                 .methodConst(cxx::type::sf::RectangleShape::fn::getGeometricCenter::id)
                                 .build(&sf::RectangleShape::getGeometricCenter));

        fns.push_back(rtl::type().member<sf::RectangleShape>()
                                 .constructor<sf::Vector2f>().build());

        fns.push_back(rtl::type().member<sf::RectangleShape>()
                                 .method(cxx::type::sf::RectangleShape::fn::setSize::id)
                                 .build(&sf::RectangleShape::setSize));

        fns.push_back(rtl::type().member<sf::RectangleShape>()
                                 .methodConst(cxx::type::sf::RectangleShape::fn::getPointCount::id)
                                 .build(&sf::RectangleShape::getPointCount));

        fns.push_back(rtl::type().member<sf::RectangleShape>()
                                 .methodConst(cxx::type::sf::RectangleShape::fn::getSize::id)
                                 .build(&sf::RectangleShape::getSize));

        fns.push_back(rtl::type().member<sf::RectangleShape>()
                                 .methodConst(cxx::type::sf::RectangleShape::fn::getPoint::id)
                                 .build(&sf::RectangleShape::getPoint));
    }
}

