
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Window/WindowBase.hpp>
#include <SFML/Window/Cursor.hpp>
#include <SFML/System/String.hpp>
#include <SFML/Window/VideoMode.hpp>
#include <SFML/Window/WindowEnums.hpp>
#include <SFML/System/Vector2.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs95::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::WindowBase>(cxx::type::sf::WindowBase::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method<sf::VideoMode, const sf::String &, unsigned int, sf::State>(cxx::type::sf::WindowBase::fn::create::id)
                                 .build(&sf::WindowBase::create));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method<sf::VideoMode, const sf::String &, sf::State>(cxx::type::sf::WindowBase::fn::create::id)
                                 .build(&sf::WindowBase::create));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .methodConst(cxx::type::sf::WindowBase::fn::hasFocus::id)
                                 .build(&sf::WindowBase::hasFocus));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .constructor<sf::VideoMode, const sf::String &, unsigned int, sf::State>().build());

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .constructor<sf::VideoMode, const sf::String &, sf::State>().build());

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::close::id)
                                 .build(&sf::WindowBase::close));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .methodConst(cxx::type::sf::WindowBase::fn::isOpen::id)
                                 .build(&sf::WindowBase::isOpen));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setMouseCursor::id)
                                 .build(&sf::WindowBase::setMouseCursor));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .methodConst(cxx::type::sf::WindowBase::fn::getPosition::id)
                                 .build(&sf::WindowBase::getPosition));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setPosition::id)
                                 .build(&sf::WindowBase::setPosition));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setKeyRepeatEnabled::id)
                                 .build(&sf::WindowBase::setKeyRepeatEnabled));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .methodConst(cxx::type::sf::WindowBase::fn::getSize::id)
                                 .build(&sf::WindowBase::getSize));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setIcon::id)
                                 .build(&sf::WindowBase::setIcon));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setSize::id)
                                 .build(&sf::WindowBase::setSize));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setTitle::id)
                                 .build(&sf::WindowBase::setTitle));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setVisible::id)
                                 .build(&sf::WindowBase::setVisible));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::requestFocus::id)
                                 .build(&sf::WindowBase::requestFocus));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setMouseCursorVisible::id)
                                 .build(&sf::WindowBase::setMouseCursorVisible));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setMouseCursorGrabbed::id)
                                 .build(&sf::WindowBase::setMouseCursorGrabbed));

        fns.push_back(rtl::type().member<sf::WindowBase>()
                                 .method(cxx::type::sf::WindowBase::fn::setJoystickThreshold::id)
                                 .build(&sf::WindowBase::setJoystickThreshold));
    }
}

