
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Graphics/Text.hpp>
#include <SFML/Graphics/Font.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs42::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Text>(cxx::type::sf::Text::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setFillColor::id)
                                 .build(&sf::Text::setFillColor));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .constructor<const sf::Font &, sf::String, unsigned int>().build());

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setOutlineColor::id)
                                 .build(&sf::Text::setOutlineColor));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setString::id)
                                 .build(&sf::Text::setString));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method<const sf::Font&>(cxx::type::sf::Text::fn::setFont::id)
                                 .build(&sf::Text::setFont));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setLineSpacing::id)
                                 .build(&sf::Text::setLineSpacing));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getOutlineThickness::id)
                                 .build(&sf::Text::getOutlineThickness));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setCharacterSize::id)
                                 .build(&sf::Text::setCharacterSize));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setLetterSpacing::id)
                                 .build(&sf::Text::setLetterSpacing));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setStyle::id)
                                 .build(&sf::Text::setStyle));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .method(cxx::type::sf::Text::fn::setOutlineThickness::id)
                                 .build(&sf::Text::setOutlineThickness));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getString::id)
                                 .build(&sf::Text::getString));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getLineSpacing::id)
                                 .build(&sf::Text::getLineSpacing));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getFont::id)
                                 .build(&sf::Text::getFont));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getCharacterSize::id)
                                 .build(&sf::Text::getCharacterSize));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getLetterSpacing::id)
                                 .build(&sf::Text::getLetterSpacing));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getStyle::id)
                                 .build(&sf::Text::getStyle));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getFillColor::id)
                                 .build(&sf::Text::getFillColor));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getOutlineColor::id)
                                 .build(&sf::Text::getOutlineColor));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::findCharacterPos::id)
                                 .build(&sf::Text::findCharacterPos));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getLocalBounds::id)
                                 .build(&sf::Text::getLocalBounds));

        fns.push_back(rtl::type().member<sf::Text>()
                                 .methodConst(cxx::type::sf::Text::fn::getGlobalBounds::id)
                                 .build(&sf::Text::getGlobalBounds));
    }
}

