
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Network/TcpListener.hpp>
#include <SFML/Network/TcpSocket.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs57::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::TcpListener>(cxx::type::sf::TcpListener::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::TcpListener>()
                                 .method(cxx::type::sf::TcpListener::fn::accept::id)
                                 .build(&sf::TcpListener::accept));

        fns.push_back(rtl::type().member<sf::TcpListener>()
                                 .methodConst(cxx::type::sf::TcpListener::fn::getLocalPort::id)
                                 .build(&sf::TcpListener::getLocalPort));

        fns.push_back(rtl::type().member<sf::TcpListener>()
                                 .method(cxx::type::sf::TcpListener::fn::listen::id)
                                 .build(&sf::TcpListener::listen));

        fns.push_back(rtl::type().member<sf::TcpListener>()
                                 .method(cxx::type::sf::TcpListener::fn::close::id)
                                 .build(&sf::TcpListener::close));
    }
}

