
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Window/Clipboard.hpp>
#include <SFML/System/String.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs71::fn {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().function(cxx::fn::sf::Clipboard::getString::id)
                                 .build(&sf::Clipboard::getString));

        fns.push_back(rtl::type().function(cxx::fn::sf::Clipboard::setString::id)
                                 .build(&sf::Clipboard::setString));
    }
}

