
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/System/String.hpp>
#include <xlocale>
#include <xstring>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs66::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::String>(cxx::type::sf::String::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<char, const std::locale &>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<wchar_t>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<char32_t>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<const char *, const std::locale &>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<const std::string &, const std::locale &>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<const wchar_t *>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<const std::wstring &>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<const char32_t *>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .constructor<std::u32string>().build());

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::toWideString::id)
                                 .build(&sf::String::toWideString));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::getSize::id)
                                 .build(&sf::String::getSize));

        fns.push_back(rtl::type().member<sf::String>()
                                 .method(cxx::type::sf::String::fn::begin::id)
                                 .build(&sf::String::begin));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::toAnsiString::id)
                                 .build(&sf::String::toAnsiString));

        fns.push_back(rtl::type().member<sf::String>()
                                 .method<unsigned long long, unsigned long long, const sf::String &>(cxx::type::sf::String::fn::replace::id)
                                 .build(&sf::String::replace));

        fns.push_back(rtl::type().member<sf::String>()
                                 .method<const sf::String &, const sf::String &>(cxx::type::sf::String::fn::replace::id)
                                 .build(&sf::String::replace));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::toUtf8::id)
                                 .build(&sf::String::toUtf8));

        fns.push_back(rtl::type().member<sf::String>()
                                 .method(cxx::type::sf::String::fn::clear::id)
                                 .build(&sf::String::clear));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::toUtf16::id)
                                 .build(&sf::String::toUtf16));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::toUtf32::id)
                                 .build(&sf::String::toUtf32));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::isEmpty::id)
                                 .build(&sf::String::isEmpty));

        fns.push_back(rtl::type().member<sf::String>()
                                 .method(cxx::type::sf::String::fn::erase::id)
                                 .build(&sf::String::erase));

        fns.push_back(rtl::type().member<sf::String>()
                                 .method(cxx::type::sf::String::fn::insert::id)
                                 .build(&sf::String::insert));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::find::id)
                                 .build(&sf::String::find));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::substring::id)
                                 .build(&sf::String::substring));

        fns.push_back(rtl::type().member<sf::String>()
                                 .methodConst(cxx::type::sf::String::fn::getData::id)
                                 .build(&sf::String::getData));

        fns.push_back(rtl::type().member<sf::String>()
                                 .method(cxx::type::sf::String::fn::end::id)
                                 .build(&sf::String::end));
    }
}


namespace regs66::type1 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::U8StringCharTraits>(cxx::type::sf::U8StringCharTraits::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::move::id)
                                 .build(&sf::U8StringCharTraits::move));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::compare::id)
                                 .build(&sf::U8StringCharTraits::compare));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::copy::id)
                                 .build(&sf::U8StringCharTraits::copy));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic<sf::U8StringCharTraits::char_type &, sf::U8StringCharTraits::char_type>(cxx::type::sf::U8StringCharTraits::fn::assign::id)
                                 .build(&sf::U8StringCharTraits::assign));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic<sf::U8StringCharTraits::char_type *, unsigned long long, sf::U8StringCharTraits::char_type>(cxx::type::sf::U8StringCharTraits::fn::assign::id)
                                 .build(&sf::U8StringCharTraits::assign));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::eq::id)
                                 .build(&sf::U8StringCharTraits::eq));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::length::id)
                                 .build(&sf::U8StringCharTraits::length));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::lt::id)
                                 .build(&sf::U8StringCharTraits::lt));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::find::id)
                                 .build(&sf::U8StringCharTraits::find));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::to_char_type::id)
                                 .build(&sf::U8StringCharTraits::to_char_type));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::not_eof::id)
                                 .build(&sf::U8StringCharTraits::not_eof));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::to_int_type::id)
                                 .build(&sf::U8StringCharTraits::to_int_type));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::eq_int_type::id)
                                 .build(&sf::U8StringCharTraits::eq_int_type));

        fns.push_back(rtl::type().member<sf::U8StringCharTraits>()
                                 .methodStatic(cxx::type::sf::U8StringCharTraits::fn::eof::id)
                                 .build(&sf::U8StringCharTraits::eof));
    }
}

