
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Audio/Sound.hpp>
#include <SFML/Audio/SoundBuffer.hpp>
#include <SFML/Audio/SoundSource.hpp>
#include <SFML/System/Time.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs9::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Sound>(cxx::type::sf::Sound::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .methodConst(cxx::type::sf::Sound::fn::getBuffer::id)
                                 .build(&sf::Sound::getBuffer));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .method(cxx::type::sf::Sound::fn::stop::id)
                                 .build(&sf::Sound::stop));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .method(cxx::type::sf::Sound::fn::pause::id)
                                 .build(&sf::Sound::pause));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .constructor<const sf::SoundBuffer &>().build());

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .method(cxx::type::sf::Sound::fn::play::id)
                                 .build(&sf::Sound::play));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .method<const sf::SoundBuffer&>(cxx::type::sf::Sound::fn::setBuffer::id)
                                 .build(&sf::Sound::setBuffer));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .method(cxx::type::sf::Sound::fn::setLooping::id)
                                 .build(&sf::Sound::setLooping));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .method(cxx::type::sf::Sound::fn::setPlayingOffset::id)
                                 .build(&sf::Sound::setPlayingOffset));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .methodConst(cxx::type::sf::Sound::fn::isLooping::id)
                                 .build(&sf::Sound::isLooping));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .methodConst(cxx::type::sf::Sound::fn::getPlayingOffset::id)
                                 .build(&sf::Sound::getPlayingOffset));

        fns.push_back(rtl::type().member<sf::Sound>()
                                 .methodConst(cxx::type::sf::Sound::fn::getStatus::id)
                                 .build(&sf::Sound::getStatus));
    }
}

