
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/Window/Context.hpp>
#include <SFML/Window/ContextSettings.hpp>
#include <SFML/System/Vector2.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs72::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Context>(cxx::type::sf::Context::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Context>()
                                 .constructor<const sf::ContextSettings &, sf::Vector2u>().build());

        fns.push_back(rtl::type().member<sf::Context>()
                                 .methodStatic(cxx::type::sf::Context::fn::getActiveContextId::id)
                                 .build(&sf::Context::getActiveContextId));

        fns.push_back(rtl::type().member<sf::Context>()
                                 .method(cxx::type::sf::Context::fn::setActive::id)
                                 .build(&sf::Context::setActive));

        fns.push_back(rtl::type().member<sf::Context>()
                                 .methodConst(cxx::type::sf::Context::fn::getSettings::id)
                                 .build(&sf::Context::getSettings));

        fns.push_back(rtl::type().member<sf::Context>()
                                 .methodStatic(cxx::type::sf::Context::fn::getActiveContext::id)
                                 .build(&sf::Context::getActiveContext));

        fns.push_back(rtl::type().member<sf::Context>()
                                 .methodStatic(cxx::type::sf::Context::fn::isExtensionAvailable::id)
                                 .build(&sf::Context::isExtensionAvailable));
    }
}

