
/*****************************************************************************
 *                                                                           *
 *  `clang-mirror` generated file.                                           *
 *                                                                           *
 *  This file is automatically generated by `clang-mirror` and represents    *
 *  the reflected projection of user code for consumption by the             *
 *  Reflection Template Library(RTL).                                        *
 *                                                                           *
 *  It contains compiler-derived identifiers and metadata describing         *
 *  namespaces, types, and members selected for reflection.                  *
 *                                                                           *
 *  DO NOT EDIT THIS FILE MANUALLY.                                          *
 *  Any changes will be overwritten by the generator.                        *
 *                                                                           *
 *  clang-mirror: https://github.com/ReflectCxx/clang-mirror                 *
 *  RTL: https://github.com/ReflectCxx/ReflectionTemplateLibrary-CPP         *
 *                                                                           *
 *****************************************************************************/


#include <SFML/System/Angle.hpp>
#include <SFML/System/Vector2.hpp>
#include <SFML/Graphics/Transformable.hpp>
#include <SFML/Graphics/Transform.hpp>

#include "../reg_ids.h"
#include "../reg_decls.h"


namespace regs46::type0 {
    void init(std::vector<rtl::Function>& fns) {

        fns.push_back(rtl::type().record<sf::Transformable>(cxx::type::sf::Transformable::id)
                                 .build());

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .method(cxx::type::sf::Transformable::fn::setPosition::id)
                                 .build(&sf::Transformable::setPosition));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .method(cxx::type::sf::Transformable::fn::setOrigin::id)
                                 .build(&sf::Transformable::setOrigin));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .method(cxx::type::sf::Transformable::fn::setRotation::id)
                                 .build(&sf::Transformable::setRotation));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .method(cxx::type::sf::Transformable::fn::setScale::id)
                                 .build(&sf::Transformable::setScale));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .methodConst(cxx::type::sf::Transformable::fn::getPosition::id)
                                 .build(&sf::Transformable::getPosition));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .methodConst(cxx::type::sf::Transformable::fn::getOrigin::id)
                                 .build(&sf::Transformable::getOrigin));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .methodConst(cxx::type::sf::Transformable::fn::getRotation::id)
                                 .build(&sf::Transformable::getRotation));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .methodConst(cxx::type::sf::Transformable::fn::getScale::id)
                                 .build(&sf::Transformable::getScale));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .method(cxx::type::sf::Transformable::fn::move::id)
                                 .build(&sf::Transformable::move));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .method(cxx::type::sf::Transformable::fn::rotate::id)
                                 .build(&sf::Transformable::rotate));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .method(cxx::type::sf::Transformable::fn::scale::id)
                                 .build(&sf::Transformable::scale));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .methodConst(cxx::type::sf::Transformable::fn::getTransform::id)
                                 .build(&sf::Transformable::getTransform));

        fns.push_back(rtl::type().member<sf::Transformable>()
                                 .methodConst(cxx::type::sf::Transformable::fn::getInverseTransform::id)
                                 .build(&sf::Transformable::getInverseTransform));
    }
}

